### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vikramdurai** [harshithAshok/phone-app#1]
- [ ]  Create and prototype app in Fuse 
- [ ]  Push compiled code to GitHub
- [ ]  Publish app to the Google Play Store
